[build]
builder = "nixpacks"

[deploy]
startCommand = "node dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[healthcheck]]
path = "/health"
timeout = 300
interval = 10

